# Generated by Django 3.0.6 on 2020-05-11 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revealed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=250)),
                ('eye', models.CharField(max_length=250)),
                ('lens', models.CharField(max_length=250)),
                ('given', models.CharField(max_length=20)),
                ('reminder', models.CharField(max_length=20)),
                ('docName', models.CharField(max_length=250)),
                ('revealDate', models.DateField(default=django.utils.timezone.now)),
                ('rSphN', models.CharField(max_length=20)),
                ('rCylN', models.CharField(max_length=20)),
                ('rAxisN', models.CharField(max_length=20)),
                ('lSphN', models.CharField(max_length=20)),
                ('lCylN', models.CharField(max_length=20)),
                ('lAxisN', models.CharField(max_length=20)),
                ('rSphF', models.CharField(max_length=20)),
                ('rCylF', models.CharField(max_length=20)),
                ('rAxisF', models.CharField(max_length=20)),
                ('lSphF', models.CharField(max_length=20)),
                ('lCylF', models.CharField(max_length=20)),
                ('lAxisF', models.CharField(max_length=20)),
                ('paName', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=False)),
                ('delStatus', models.BooleanField(default=False)),
                ('ann', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('img', models.ImageField(blank=True, default='glasses.jpg', max_length=150, null=True, upload_to='media')),
                ('quan', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=250)),
            ],
        ),
    ]
